apiVersion: apps/v1
kind: Deployment
metadata:
  name: hudapobuda-staging-deployment
  labels:
    app: hudapobuda-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hudapobuda-staging
  template:
    metadata:
      labels:
        app: hudapobuda-staging
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: hudapobuda-staging-storage
          emptyDir: {}
      initContainers:
        - name: collectstatic
          image: hudapobuda-staging
          volumeMounts:
            - name: hudapobuda-staging-storage
              mountPath: /storage
          command:
            - python
            - manage.py
            - collectstatic
            - --no-input
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: hudapobuda.settings.production
          envFrom:
            - secretRef:
                name: hudapobuda-staging-credentials
          resources:
            requests:
              memory: 1Gi
              cpu: 200m
            limits:
              memory: 1Gi
              cpu: 200m
        - name: migrate
          image: hudapobuda-staging
          command:
            - python
            - manage.py
            - migrate
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: hudapobuda.settings.production
          envFrom:
            - secretRef:
                name: hudapobuda-staging-credentials
          resources:
            requests:
              memory: 1Gi
              cpu: 200m
            limits:
              memory: 1Gi
              cpu: 200m
      containers:
        - name: hudapobuda-staging
          image: hudapobuda-staging
          volumeMounts:
            - name: hudapobuda-staging-storage
              mountPath: /storage
          command:
            - gunicorn
            - hudapobuda.wsgi:application
            - -b
            - 0.0.0.0:8000
            - --log-level
            - DEBUG
          ports:
            - containerPort: 8000
          envFrom:
              - secretRef:
                  name: hudapobuda-staging-credentials
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: hudapobuda.settings.production
          resources:
            requests:
              memory: 1Gi
              cpu: 200m
            limits:
              memory: 1Gi
              cpu: 200m
        - name: hudapobuda-staging-nginx
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          image: nginx:alpine
          volumeMounts:
            - name: hudapobuda-staging-storage
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              memory: 500Mi
              cpu: 100m
            limits:
              memory: 500Mi
              cpu: 100m
