apiVersion: apps/v1
kind: Deployment
metadata:
  name: hudapobuda-deployment
  labels:
    app: hudapobuda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hudapobuda
  template:
    metadata:
      labels:
        app: hudapobuda
    spec:
      nodeName: scw-djnd-test-cluster-djnd-beefier-pool-ee8640
      securityContext:
        fsGroup: 1000
      volumes:
        - name: hudapobuda-storage
          emptyDir: {}
      initContainers:
        - name: collectstatic
          image: hudapobuda
          volumeMounts:
            - name: hudapobuda-storage
              mountPath: /storage
          command:
            - python
            - manage.py
            - collectstatic
            - --no-input
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: hudapobuda.settings.production
          envFrom:
            - secretRef:
                name: hudapobuda-credentials
          resources:
            requests:
              memory: 1Gi
              cpu: 200m
            limits:
              memory: 1Gi
              cpu: 200m
        - name: migrate
          image: hudapobuda
          command:
            - python
            - manage.py
            - migrate
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: hudapobuda.settings.production
          envFrom:
            - secretRef:
                name: hudapobuda-credentials
          resources:
            requests:
              memory: 1Gi
              cpu: 200m
            limits:
              memory: 1Gi
              cpu: 200m
      containers:
        - name: hudapobuda
          image: hudapobuda
          volumeMounts:
            - name: hudapobuda-storage
              mountPath: /storage
          command:
            - gunicorn
            - hudapobuda.wsgi:application
            - -b
            - 0.0.0.0:8000
            - --log-level
            - DEBUG
            - --workers
            - "1"
            - --threads
            - "3"
            - --timeout
            - "90"
          ports:
            - containerPort: 8000
          envFrom:
              - secretRef:
                  name: hudapobuda-credentials
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: hudapobuda.settings.production
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 100m
        - name: hudapobuda-nginx
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          image: nginx:alpine
          volumeMounts:
            - name: hudapobuda-storage
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 50Mi
              cpu: 50m
