apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hudapobuda
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: hudapobuda
    newName: rg.fr-par.scw.cloud/djnd/hudapobuda
    newTag: '585723d1ff34547f2c30fb452489a4dda19801f1'
