apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hudapobuda-staging-pvc
  labels:
    app: hudapobuda-staging
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  storageClassName: 'scw-bssd'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
