
version: '3'

volumes:
  postgres-data:

services:
  wagtail:
    build: ./hudapobuda
    working_dir: /app
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./hudapobuda:/app:delegated,rw
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://wagtail:changeme@db/pmvd
      PYTHONPATH: /app:$PYTHONPATH
    depends_on:
      - db

  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: wagtail
      POSTGRES_DB: wagtail
      POSTGRES_PASSWORD: changeme
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    expose:
      - "5432"
