# Generated by Django 3.1.10 on 2021-05-07 19:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210507_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metasettings',
            name='header_links',
            field=wagtail.core.fields.StreamField([('page_link', wagtail.core.blocks.StructBlock([('style', wagtail.core.blocks.ChoiceBlock(choices=[('plain', 'Navaden'), ('button', 'Gumb')], label='Stil povezave')), ('name', wagtail.core.blocks.CharBlock(help_text='Če je prazno se uporabi naslov strani.', label='Ime', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(label='Stran'))])), ('external_link', wagtail.core.blocks.StructBlock([('style', wagtail.core.blocks.ChoiceBlock(choices=[('plain', 'Navaden'), ('button', 'Gumb')], label='Stil povezave')), ('name', wagtail.core.blocks.CharBlock(label='Ime')), ('url', wagtail.core.blocks.URLBlock(label='Povezava'))]))]),
        ),
    ]
