# Generated by Django 3.2.3 on 2021-05-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_formfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='metasettings',
            name='share_email_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
