# Generated by Django 3.2.3 on 2021-05-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_metasettings_share_email_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='metasettings',
            name='share_twitter_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
