# Generated by Django 3.1.10 on 2021-10-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20211012_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativepage',
            name='share_box_mail_subject',
            field=models.TextField(default='Huda pobuda', verbose_name='Delitev - zadeva maila'),
            preserve_default=False,
        ),
    ]
