# Generated by Django 3.1.10 on 2021-10-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_initiativepage_share_box_mail_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativepage',
            name='share_box_mail',
            field=models.TextField(blank=True, null=True, verbose_name='Delitev - besedilo maila'),
        ),
        migrations.AlterField(
            model_name='initiativepage',
            name='share_box_mail_subject',
            field=models.TextField(blank=True, null=True, verbose_name='Delitev - zadeva maila'),
        ),
        migrations.AlterField(
            model_name='initiativepage',
            name='share_box_tw',
            field=models.TextField(blank=True, null=True, verbose_name='Delitev - besedilo twitter objave'),
        ),
    ]
