# Generated by Django 3.1.10 on 2021-10-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20211013_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hide_header',
            field=models.BooleanField(default=False, verbose_name='Skrij naslovno sekcijo'),
        ),
    ]
