# Generated by Django 3.1.10 on 2021-10-14 13:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0021_homepage_hide_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('body', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Vsebina')),
            ],
            options={
                'verbose_name': 'Urejanje naročnine',
                'verbose_name_plural': 'Urejanja naročnin',
            },
            bases=('wagtailcore.page',),
        ),
    ]
