# Generated by Django 3.1.10 on 2021-10-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_newsletterpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterpage',
            name='newsletter_button',
            field=models.TextField(blank=True, null=True, verbose_name='Gumb'),
        ),
        migrations.AddField(
            model_name='newsletterpage',
            name='newsletter_checkbox',
            field=models.TextField(blank=True, null=True, verbose_name='Tekst ob checkboxu'),
        ),
        migrations.AddField(
            model_name='newsletterpage',
            name='newsletter_label',
            field=models.TextField(blank=True, null=True, verbose_name='Tekst nad poljem za vnos maila'),
        ),
    ]
