# Generated by Django 3.1.10 on 2021-11-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20211015_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativepage',
            name='hide_donations',
            field=models.BooleanField(default=False, verbose_name='Skrij donacije?'),
        ),
    ]
