# Generated by Django 3.2.9 on 2021-11-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20211118_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativepage',
            name='hide_socials',
            field=models.BooleanField(default=False, verbose_name='Skrij škatlo za deljenje?'),
        ),
        migrations.AlterField(
            model_name='initiativepage',
            name='share_box_mail',
            field=models.TextField(blank=True, null=True, verbose_name='Deljenje - besedilo maila'),
        ),
        migrations.AlterField(
            model_name='initiativepage',
            name='share_box_mail_subject',
            field=models.TextField(blank=True, null=True, verbose_name='Deljenje - zadeva maila'),
        ),
        migrations.AlterField(
            model_name='initiativepage',
            name='share_box_title',
            field=models.CharField(max_length=255, verbose_name='Škatla za deljenje - naslov'),
        ),
        migrations.AlterField(
            model_name='initiativepage',
            name='share_box_tw',
            field=models.TextField(blank=True, null=True, verbose_name='Deljenje - besedilo twitter objave'),
        ),
    ]
